// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Regulation.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClientAvailableRegulationModel
    {
        /// <summary>
        /// Initializes a new instance of the ClientAvailableRegulationModel
        /// class.
        /// </summary>
        public ClientAvailableRegulationModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClientAvailableRegulationModel
        /// class.
        /// </summary>
        public ClientAvailableRegulationModel(string clientId = default(string), string regulationId = default(string))
        {
            ClientId = clientId;
            RegulationId = regulationId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RegulationId")]
        public string RegulationId { get; set; }

    }
}
