// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Regulation.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClientRegulationModel
    {
        /// <summary>
        /// Initializes a new instance of the ClientRegulationModel class.
        /// </summary>
        public ClientRegulationModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClientRegulationModel class.
        /// </summary>
        public ClientRegulationModel(string id = default(string), string clientId = default(string), string regulationId = default(string), bool? kyc = default(bool?), bool? active = default(bool?))
        {
            Id = id;
            ClientId = clientId;
            RegulationId = regulationId;
            Kyc = kyc;
            Active = active;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RegulationId")]
        public string RegulationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Kyc")]
        public bool? Kyc { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Active")]
        public bool? Active { get; set; }

    }
}
