// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Regulation.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClientMarginRegulationModel
    {
        /// <summary>
        /// Initializes a new instance of the ClientMarginRegulationModel
        /// class.
        /// </summary>
        public ClientMarginRegulationModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClientMarginRegulationModel
        /// class.
        /// </summary>
        public ClientMarginRegulationModel(string regulationId = default(string))
        {
            RegulationId = regulationId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RegulationId")]
        public string RegulationId { get; set; }

    }
}
