// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Regulation.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RegulationModel
    {
        /// <summary>
        /// Initializes a new instance of the RegulationModel class.
        /// </summary>
        public RegulationModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RegulationModel class.
        /// </summary>
        public RegulationModel(string id = default(string), string profileType = default(string), string termsOfUseUrl = default(string), string riskDescriptionUrl = default(string), string marginTradingConditions = default(string))
        {
            Id = id;
            ProfileType = profileType;
            TermsOfUseUrl = termsOfUseUrl;
            RiskDescriptionUrl = riskDescriptionUrl;
            MarginTradingConditions = marginTradingConditions;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProfileType")]
        public string ProfileType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TermsOfUseUrl")]
        public string TermsOfUseUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RiskDescriptionUrl")]
        public string RiskDescriptionUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MarginTradingConditions")]
        public string MarginTradingConditions { get; set; }

    }
}
