// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Regulation.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class WelcomeRegulationRuleModel
    {
        /// <summary>
        /// Initializes a new instance of the WelcomeRegulationRuleModel class.
        /// </summary>
        public WelcomeRegulationRuleModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WelcomeRegulationRuleModel class.
        /// </summary>
        public WelcomeRegulationRuleModel(string id = default(string), string country = default(string), string regulationId = default(string))
        {
            Id = id;
            Country = country;
            RegulationId = regulationId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Country")]
        public string Country { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RegulationId")]
        public string RegulationId { get; set; }

    }
}
